services:
    backend_service:
        container_name: backend
        build: ./backend/
        command: [ "uv", "run", "uvicorn", "app.main:app", "--reload", "--proxy-headers", "--host", "0.0.0.0", "--port", "8000" ]
        ports:
            - "8000:8000"
